version: "3"
services:
  jasmin:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    container_name: jasmin
    volumes:
      - ./jasmin:/usr/jasmin/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    env_file: .env
    depends_on:
      - redis
      - rabbit-mq
  redis:
    image: redis:alpine
  rabbit-mq:
    image: rabbitmq:alpine
