version: "3"

services:
  redis:
    image: redis:alpine

  rabbit-mq:
    image: rabbitmq:alpine

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    #ports:
    #  - '9090:9090'
    volumes:
      - ./misc/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - monitoring_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - jasmin

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - monitoring_data:/var/lib/grafana
    depends_on:
      - prometheus

  jasmin:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    container_name: jasmin
    volumes:
      - ./jasmin:/usr/jasmin/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - redis
      - rabbit-mq
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq

volumes:
  monitoring_data: { }
