version: "3"
services:
    jasmin:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.dev
        container_name: jasmin
        volumes:
            - ./jasmin:/usr/jasmin/jasmin
            - ./tests:/usr/jasmin/tests
        ports: 
            - 2775:2775
            - 8990:8990
            - 1401:1401
        env_file: .env

    jasmin-alpine:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.alpine
        container_name: jasmin-alpine
        env_file: .env
