apiVersion: v1
kind: Pod
metadata:
  name: jasmin
  labels:
    app: jasmin
spec:
  hostname: jasmin
  subdomain: app
  containers:
    - name: jasmin
      image: jookies/jasmin:latest
      ports:
        - containerPort: 2775
          name: smpp-port
          protocol: TCP
        - containerPort: 1401
          name: http-port
          protocol: TCP
        - containerPort: 8990
          name: cli-port
          protocol: TCP
      lifecycle:
        postStart:
          exec:
            command: [ "sh", "-c", "cp /tmp/jasminconfig/* /etc/jasmin/" ]
      volumeMounts:
        - name: jasminconfig
          mountPath: /tmp/jasminconfig
  volumes:
    - name: jasminconfig
      configMap:
        name: etcjasmin
