apiVersion: v1
kind: Pod
metadata:
  name: rabbit
  labels:
    name: rabbit
spec:
  hostname: rabbit
  subdomain: mq
  containers:
  - name: rabbit
    image: rabbitmq:3.10-management-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: mq
spec:
  selector:
    name: rabbit
  clusterIP: None

