name: continuous integration jobs

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - '0.9'
      - '0.10'
      - '0.10.*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install os dependencies
        run: |
          sudo apt-get install -y python-dev libffi-dev libffi-dev bc
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install production dependencies
        run: pip install -r ./requirements.txt
      - name: Install test dependencies
        run: pip install -r ./requirements-test.txt
      - name: Pre-test preps
        run: |
          sudo sudo mkdir -p /var/log/jasmin /etc/jasmin
          ls -l /etc/jasmin
          sudo sudo ln -s ./misc/config /etc/jasmin
          ls -l ./misc/config
          ls -l /etc/jasmin
          sudo chmod -R 777 /var/log/jasmin /etc/jasmin/store
          chmod +x ./misc/pylint/run.sh
      - name: Run tests
        run: |
          ./misc/pylint/run.sh
          coverage run --source=jasmin -m twisted.trial tests
          coveralls
          cd misc/doc;make html;cd ../../
